"""
Scores fine-mapping candidate SNPs with Borzoi (all 4 replicates).
Steps:
  1. Read VCF (hg38) generated by fine_mapping_post_processing.py
  2. Run borzoi_sad.py for each of the 4 model replicates
Output: borzoi_results/{f3c0..f3c3}/sad.h5  (n_snps x n_tracks SAD matrix)

The VCF (candidates_hg38_borzoi.vcf) is produced by fine_mapping_post_processing.py,
which does the liftover hg19→hg38 directly from the fine-mapping candidates.
"""

import os
import subprocess

# ── Paths ─────────────────────────────────────────────────────────────────────
BORZOI_DIR   = '/private/home/rsmerigl/codes/cleaned_codes/borzoi'
OUTPUT_BASE  = '/private/groups/ioannidislab/smeriglio/out_cleaned_codes/vcf_files_windows/ukbb/borzoi_results'
VCF_FILE     = os.path.join(OUTPUT_BASE, 'candidates_hg38_borzoi.vcf')

PARAMS_JSON  = os.path.join(BORZOI_DIR, 'examples/params_pred.json')
TARGETS_FILE = os.path.join(BORZOI_DIR, 'examples/targets_human.txt')
BORZOI_SAD   = os.path.join(BORZOI_DIR, 'src/scripts/borzoi_sad.py')

FOLDS = ['f3c0', 'f3c1', 'f3c2', 'f3c3']

os.makedirs(OUTPUT_BASE, exist_ok=True)

if not os.path.exists(VCF_FILE):
    raise FileNotFoundError(
        f'VCF not found: {VCF_FILE}\n'
        'Run fine_mapping_post_processing.py first to generate it.'
    )

print(f'Using VCF: {VCF_FILE}')

# ── Run borzoi_sad.py for each fold ───────────────────────────────────────────
env = os.environ.copy()
env['BORZOI_HG38'] = os.path.join(BORZOI_DIR, 'examples/hg38')
env['BORZOI_DIR']  = BORZOI_DIR

for fold in FOLDS:
    model_h5   = os.path.join(BORZOI_DIR, f'examples/saved_models/{fold}/train/model0_best.h5')
    output_dir = os.path.join(OUTPUT_BASE, fold)
    os.makedirs(output_dir, exist_ok=True)

    sad_out = os.path.join(output_dir, 'sad.h5')
    if os.path.exists(sad_out):
        print(f'[{fold}] sad.h5 already exists, skipping')
        continue

    cmd = [
        'python', BORZOI_SAD,
        '--rc',
        '--stats', 'SAD',
        '-t', TARGETS_FILE,
        '-o', output_dir,
        PARAMS_JSON,
        model_h5,
        VCF_FILE,
    ]

    print(f'\n[{fold}] Running: {" ".join(cmd)}')
    result = subprocess.run(cmd, check=False, env=env)
    if result.returncode != 0:
        print(f'[{fold}] ERROR: exit code {result.returncode}')
    else:
        print(f'[{fold}] Done → {output_dir}')

print('\nAll folds complete.')
print(f'Output: {OUTPUT_BASE}/')
