#!/bin/bash
#SBATCH --partition=long
#SBATCH --job-name=pickle_object_creation
#SBATCH --output=/private/home/rsmerigl/codes/pre-processing/my_job_output.txt
#SBATCH --error=/private/home/rsmerigl/codes/pre-processing/my_job_error.txt
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=7-00:00:00
#SBATCH --mem=512G

source /private/home/rsmerigl/anaconda3/bin/activate /private/home/rsmerigl/anaconda3/envs/admixture
python /private/home/rsmerigl/codes/pre-processing/pickle_object_creation.py